baseURL = 'https://losangeles971.github.io/bluepulsar971/'
languageCode = 'en-us'
title = ''
theme = "ananke"
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
canonifyurls = true

[languages]
  [languages.en]
    title = "@bluepulsar971"
    weight = 1
    contentDir = "content/en"
  [languages.it]
    title = "@bluepulsar971"
    weight = 2
    contentDir = "content/it"

[params]
  text_color = ""
  author = "@bluepulsar971"
  favicon = ""
  site_logo = ""
  description = ""
  background_color_class = "bg-black"
  recent_posts_number = 10

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/bluepulsar971"
